params:
  cookie_banner:
    enable: false
baseURL: https://classcode-site.netlify.app/
defaultContentLanguage: fr
languageCode: fr
languages:
  fr:
    title: Class’Code
theme: osuny-hugo-theme
paginate: 18
permalinks:
  posts:          /actualites/:year/:month/:day/:slug/
  categories:     /actualites/:slug/
  pages:          /:slug/
taxonomies:
  administrator:  administrators
  author:         authors
  category:       categories
  researcher:     researchers
  teacher:        teachers
